import { readFile, writeFile } from "fs/promises";
import { join, basename } from "path";
import type { ProofManifest, ProofEntry, ReportFormat } from "./types";

export async function generateReport(
  manifest: ProofManifest,
  runDir: string,
  format: ReportFormat,
): Promise<string> {
  switch (format) {
    case "md":
      return generateMd(manifest, runDir);
    case "html":
      return generateHtml(manifest, runDir, false);
    case "archive":
      return generateHtml(manifest, runDir, true);
  }
}

function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString("en-US", { hour12: false });
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function modeIcon(mode: string): string {
  return mode === "browser" ? "🌐" : "🖥";
}

function entrySource(entry: ProofEntry): string {
  if (entry.testFile) return `\`${basename(entry.testFile)}\``;
  if (entry.command) return `\`${entry.command}\``;
  return entry.mode;
}

// --- Markdown ---

function generateMd(manifest: ProofManifest, runDir: string): Promise<string> {
  const lines: string[] = [];

  lines.push(`# Proof Report`);
  lines.push(``);
  lines.push(`**App:** ${manifest.appName}`);
  lines.push(`**Run:** ${manifest.run}`);
  lines.push(`**Date:** ${formatDate(manifest.createdAt)}`);
  lines.push(`**Entries:** ${manifest.entries.length}`);
  lines.push(``);

  // Summary table
  lines.push(`| # | Label | Mode | Duration | Artifact |`);
  lines.push(`|---|-------|------|----------|----------|`);
  manifest.entries.forEach((entry, i) => {
    const label = entry.label ?? entry.mode;
    lines.push(`| ${i + 1} | ${modeIcon(entry.mode)} ${label} | ${entry.mode} | ${formatDuration(entry.duration)} | [${entry.artifact}](./${entry.artifact}) |`);
  });
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Detail sections
  for (const entry of manifest.entries) {
    lines.push(`### ${modeIcon(entry.mode)} ${entry.label ?? entry.mode}`);
    lines.push(``);
    lines.push(`${entry.description}`);
    lines.push(``);
    lines.push(`- **Time:** ${formatTime(entry.timestamp)}`);
    lines.push(`- **Duration:** ${formatDuration(entry.duration)}`);
    if (entry.command) lines.push(`- **Command:** \`${entry.command}\``);
    if (entry.testFile) lines.push(`- **Test file:** \`${basename(entry.testFile)}\``);
    if (entry.testName) lines.push(`- **Test name:** ${entry.testName}`);
    lines.push(`- **Artifact:** [${entry.artifact}](./${entry.artifact})`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by [@varops/proof](https://www.npmjs.com/package/@varops/proof)*`);

  const md = lines.join("\n");
  const outPath = join(runDir, "report.md");
  return writeFile(outPath, md, "utf-8").then(() => outPath);
}

// --- HTML (shared by html and archive) ---

async function generateHtml(
  manifest: ProofManifest,
  runDir: string,
  inline: boolean,
): Promise<string> {
  const entriesHtml: string[] = [];

  for (const entry of manifest.entries) {
    const mediaHtml = await buildMediaEmbed(entry, runDir, inline);
    entriesHtml.push(`
      <div class="entry">
        <div class="entry-header">
          <span class="mode-icon">${modeIcon(entry.mode)}</span>
          <h2>${esc(entry.label ?? entry.mode)}</h2>
          <span class="badge ${entry.mode}">${entry.mode}</span>
          <span class="time">${formatTime(entry.timestamp)}</span>
        </div>
        <p class="description">${esc(entry.description)}</p>
        <div class="media">${mediaHtml}</div>
        <div class="meta">
          ${entry.command ? `<span><strong>Command:</strong> <code>${esc(entry.command)}</code></span>` : ""}
          ${entry.testFile ? `<span><strong>Test:</strong> <code>${esc(basename(entry.testFile))}</code></span>` : ""}
          ${entry.testName ? `<span><strong>Test name:</strong> ${esc(entry.testName)}</span>` : ""}
          <span><strong>Duration:</strong> ${formatDuration(entry.duration)}</span>
        </div>
      </div>`);
  }

  const totalDuration = manifest.entries.reduce((sum, e) => sum + e.duration, 0);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Proof Report — ${esc(manifest.appName)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0d1117;
    color: #e6edf3;
    line-height: 1.6;
    padding: 0;
  }
  .container { max-width: 960px; margin: 0 auto; padding: 32px 24px; }

  /* Header */
  .header {
    border-bottom: 1px solid #30363d;
    padding-bottom: 24px;
    margin-bottom: 32px;
  }
  .header h1 {
    font-size: 28px;
    font-weight: 600;
    margin-bottom: 8px;
  }
  .header h1 .app-name { color: #58a6ff; }
  .header-meta {
    display: flex;
    gap: 24px;
    color: #8b949e;
    font-size: 14px;
    flex-wrap: wrap;
  }
  .header-meta strong { color: #e6edf3; }

  /* Summary */
  .summary {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 16px;
    margin-bottom: 32px;
  }
  .stat {
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 16px;
    text-align: center;
  }
  .stat .value { font-size: 24px; font-weight: 600; color: #58a6ff; }
  .stat .label { font-size: 12px; color: #8b949e; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 4px; }

  /* Entries */
  .entry {
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    margin-bottom: 24px;
    overflow: hidden;
  }
  .entry-header {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 16px 20px;
    border-bottom: 1px solid #30363d;
  }
  .entry-header h2 { font-size: 18px; font-weight: 600; flex: 1; }
  .mode-icon { font-size: 20px; }
  .badge {
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 12px;
    font-weight: 500;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  .badge.terminal { background: #1f2a1f; color: #3fb950; border: 1px solid #238636; }
  .badge.browser { background: #1a2233; color: #58a6ff; border: 1px solid #1f6feb; }
  .time { color: #8b949e; font-size: 13px; font-family: monospace; }
  .description { padding: 16px 20px 0; color: #c9d1d9; }

  .media { padding: 0; }
  .media video {
    width: 100%;
    border-radius: 6px;
    background: #000;
  }
  .media iframe {
    width: 100%;
    height: 540px;
    border: none;
    border-radius: 6px;
    background: transparent;
  }

  /* Meta */
  .meta {
    display: flex;
    flex-wrap: wrap;
    gap: 16px;
    padding: 12px 20px 16px;
    font-size: 13px;
    color: #8b949e;
  }
  .meta strong { color: #c9d1d9; }
  .meta code {
    background: #21262d;
    padding: 1px 6px;
    border-radius: 3px;
    font-size: 12px;
    color: #e6edf3;
  }

  /* Footer */
  .footer {
    border-top: 1px solid #30363d;
    padding-top: 24px;
    margin-top: 16px;
    text-align: center;
    color: #484f58;
    font-size: 13px;
  }
  .footer a { color: #58a6ff; text-decoration: none; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Proof Report — <span class="app-name">${esc(manifest.appName)}</span></h1>
    <div class="header-meta">
      <span><strong>Run:</strong> ${esc(manifest.run)}</span>
      <span><strong>Date:</strong> ${formatDate(manifest.createdAt)}</span>
      <span><strong>Time:</strong> ${formatTime(manifest.createdAt)}</span>
    </div>
  </div>

  <div class="summary">
    <div class="stat"><div class="value">${manifest.entries.length}</div><div class="label">Captures</div></div>
    <div class="stat"><div class="value">${manifest.entries.filter(e => e.mode === "terminal").length}</div><div class="label">Terminal</div></div>
    <div class="stat"><div class="value">${manifest.entries.filter(e => e.mode === "browser").length}</div><div class="label">Browser</div></div>
    <div class="stat"><div class="value">${formatDuration(totalDuration)}</div><div class="label">Total Duration</div></div>
  </div>

  ${entriesHtml.join("\n")}

  <div class="footer">
    Generated by <a href="https://www.npmjs.com/package/@varops/proof">@varops/proof</a>
  </div>
</div>
</body>
</html>`;

  const ext = inline ? "archive.html" : "report.html";
  const outPath = join(runDir, ext);
  await writeFile(outPath, html, "utf-8");
  return outPath;
}

async function buildMediaEmbed(
  entry: ProofEntry,
  runDir: string,
  inline: boolean,
): Promise<string> {
  const artifactPath = join(runDir, entry.artifact);

  if (entry.mode === "browser") {
    if (inline) {
      const videoData = await readFile(artifactPath);
      const ext = entry.artifact.endsWith(".mp4") ? "mp4" : "webm";
      const b64 = videoData.toString("base64");
      return `<video controls autoplay muted loop src="data:video/${ext};base64,${b64}"></video>`;
    }
    return `<video controls autoplay muted loop src="./${esc(entry.artifact)}"></video>`;
  }

  if (entry.mode === "terminal") {
    if (inline) {
      const playerHtml = await readFile(artifactPath, "utf-8");
      return `<iframe allowtransparency="true" srcdoc="${escAttr(playerHtml)}"></iframe>`;
    }
    return `<iframe allowtransparency="true" src="./${esc(entry.artifact)}"></iframe>`;
  }

  return `<a href="./${esc(entry.artifact)}">${esc(entry.artifact)}</a>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function escAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
