import { readFile, writeFile } from "fs/promises";
import { join, basename } from "path";
import type { ProofManifest, ProofEntry, ReportFormat } from "./types";

export async function generateReport(
  manifest: ProofManifest,
  runDir: string,
  format: ReportFormat,
): Promise<string> {
  switch (format) {
    case "md":
      return generateMd(manifest, runDir);
    case "html":
      return generateHtml(manifest, runDir, false);
    case "archive":
      return generateHtml(manifest, runDir, true);
  }
}

function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString("en-US", { hour12: false });
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function modeIcon(mode: string): string {
  return mode === "browser" ? "🌐" : "🖥";
}

// --- Markdown ---

function generateMd(manifest: ProofManifest, runDir: string): Promise<string> {
  const lines: string[] = [];
  const totalDuration = manifest.entries.reduce((sum, e) => sum + e.duration, 0);

  lines.push(`# Proof Report`);
  lines.push(``);
  lines.push(`**App:** ${manifest.appName}`);
  lines.push(`**Run:** ${manifest.run}`);
  lines.push(`**Date:** ${formatDate(manifest.createdAt)}`);
  lines.push(`**Entries:** ${manifest.entries.length}`);
  if (manifest.description) {
    lines.push(``);
    lines.push(manifest.description);
  }
  lines.push(``);

  lines.push(`| # | Label | Mode | Duration | Artifact |`);
  lines.push(`|---|-------|------|----------|----------|`);
  manifest.entries.forEach((entry, i) => {
    const label = entry.label ?? entry.mode;
    lines.push(`| ${i + 1} | ${modeIcon(entry.mode)} ${label} | ${entry.mode} | ${formatDuration(entry.duration)} | [${entry.artifact}](./${entry.artifact}) |`);
  });
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  for (const entry of manifest.entries) {
    lines.push(`### ${modeIcon(entry.mode)} ${entry.label ?? entry.mode}`);
    lines.push(``);
    lines.push(`${entry.description}`);
    lines.push(``);
    lines.push(`- **Time:** ${formatTime(entry.timestamp)}`);
    lines.push(`- **Duration:** ${formatDuration(entry.duration)}`);
    if (entry.command) lines.push(`- **Command:** \`${entry.command}\``);
    if (entry.testFile) lines.push(`- **Test file:** \`${basename(entry.testFile)}\``);
    if (entry.testName) lines.push(`- **Test name:** ${entry.testName}`);
    lines.push(`- **Artifact:** [${entry.artifact}](./${entry.artifact})`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by [@varops/proof](https://www.npmjs.com/package/@varops/proof)*`);

  const md = lines.join("\n");
  const outPath = join(runDir, "report.md");
  return writeFile(outPath, md, "utf-8").then(() => outPath);
}

// --- HTML (shared by html and archive) ---

async function generateHtml(
  manifest: ProofManifest,
  runDir: string,
  inline: boolean,
): Promise<string> {
  const totalDuration = manifest.entries.reduce((sum, e) => sum + e.duration, 0);
  const terminalCount = manifest.entries.filter(e => e.mode === "terminal").length;
  const browserCount = manifest.entries.filter(e => e.mode === "browser").length;

  const sections: string[] = [];
  for (const entry of manifest.entries) {
    const mediaHtml = await buildMediaEmbed(entry, runDir, inline);
    const label = entry.label ?? entry.mode;
    const isTerminal = entry.mode === "terminal";
    const badgeClass = isTerminal
      ? "text-green-800 bg-emerald-100/80"
      : "text-blue-800 bg-sky-100";
    const modeLabel = isTerminal ? "Terminal" : "Browser";

    let sourceHtml = "";
    if (entry.command) {
      sourceHtml = `
          <p class="font-medium text-sm mt-4 mb-1">Command:</p>
          <div class="font-mono text-xs border px-1 rounded bg-neutral-50 border-neutral-200 subpixel-antialiased w-fit">${esc(entry.command)}</div>`;
    } else if (entry.testFile) {
      sourceHtml = `
          <p class="font-medium text-sm mt-4 mb-1">Test:</p>
          <div class="font-mono text-xs border px-1 rounded bg-neutral-50 border-neutral-200 subpixel-antialiased w-fit">${esc(basename(entry.testFile))}</div>`;
    }

    sections.push(`
      <section class="mt-12 grid-cols-12 gap-x-6 border-t border-neutral-200 pt-12 md:grid">
        <div class="col-span-5">
          <h2 class="text-2xl mb-2">${esc(label)}</h2>
          <div class="flex items-center space-x-4 subpixel-antialiased">
            <span class="rounded ${badgeClass} px-2 py-0.5 text-sm">${modeLabel}</span>
            <time class="font-mono text-[13px]">${formatTime(entry.timestamp)} (${formatDuration(entry.duration)})</time>
          </div>
          <p class="opacity-80 my-4">${esc(entry.description)}</p>
        </div>
        <div class="col-span-7">
          ${mediaHtml}
          ${sourceHtml}
        </div>
      </section>`);
  }

  const descriptionHtml = manifest.description
    ? `<p class="max-w-2xl leading-relaxed opacity-80">${esc(manifest.description)}</p>`
    : "";

  const badgesHtml = [
    terminalCount > 0 ? `<span class="whitespace-nowrap rounded font-medium text-green-800 bg-emerald-100/80 px-2 py-0.5 text-sm">${terminalCount} Terminal</span>` : "",
    browserCount > 0 ? `<span class="whitespace-nowrap rounded font-medium text-blue-800 bg-sky-100 px-2 py-0.5 text-sm">${browserCount} Browser</span>` : "",
  ].filter(Boolean).join("\n        ");

  const tailwindScript = inline
    ? `<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>`
    : `<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover">
<meta http-equiv="cleartype" content="on">
<title>Proof Report - ${esc(manifest.run)}</title>
${tailwindScript}
</head>
<body>

<div class="container mx-auto px-6 my-14 w-full max-w-5xl antialiased">
  <header>
    <div class="flex items-center space-x-4 mb-6">
      <h1 class="text-4xl leading-none font-medium">Proof report</h1>
      <span class="mt-2 rounded bg-neutral-100 px-2 py-1 font-mono text-sm leading-none">${esc(manifest.run)}</span>
    </div>

    ${descriptionHtml}

    <div class="mt-6 md:flex md:items-center md:space-x-4 leading-none">
      <span class="block mb-2 md:inline md:m-0">${formatDate(manifest.createdAt)} &middot; ${formatTime(manifest.createdAt)} (${formatDuration(totalDuration)})</span>
      ${badgesHtml}
    </div>

    <p class="my-6">Generated by <a href="https://www.npmjs.com/package/@varops/proof" class="font-medium text-blue-600">@varops/proof</a></p>
  </header>

  <main>
    ${sections.join("\n")}
  </main>

  <footer></footer>
</div>

</body>
</html>`;

  const ext = inline ? "archive.html" : "report.html";
  const outPath = join(runDir, ext);
  await writeFile(outPath, html, "utf-8");
  return outPath;
}

async function buildMediaEmbed(
  entry: ProofEntry,
  runDir: string,
  inline: boolean,
): Promise<string> {
  const artifactPath = join(runDir, entry.artifact);

  if (entry.mode === "browser") {
    if (inline) {
      const videoData = await readFile(artifactPath);
      const ext = entry.artifact.endsWith(".mp4") ? "mp4" : "webm";
      const b64 = videoData.toString("base64");
      return `<video class="bg-black w-full shadow-xs rounded-md aspect-3/2" controls muted loop src="data:video/${ext};base64,${b64}"></video>`;
    }
    return `<video class="bg-neutral-200 w-full rounded-md aspect-3/2" controls muted loop src="./${esc(entry.artifact)}"></video>`;
  }

  if (entry.mode === "terminal") {
    if (inline) {
      const playerHtml = await readFile(artifactPath, "utf-8");
      return `<iframe class="w-full aspect-3/2 rounded-lg bg-black" allowtransparency="true" srcdoc="${escAttr(playerHtml)}"></iframe>`;
    }
    return `<iframe class="w-full aspect-3/2 rounded-lg bg-black" allowtransparency="true" src="./${esc(entry.artifact)}"></iframe>`;
  }

  return `<a href="./${esc(entry.artifact)}">${esc(entry.artifact)}</a>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function escAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
